version: 2.1

#Comment

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    machine: true   
    resource_class: brianoh1979/brian-winrunner
    steps:
      - checkout
      - run: 
          name: "See where we are"
          shell: powershell
          command: |
            dir
      - run: 
          name: "Docker image build and tag"
          shell: powershell.exe
          command: |
            C:\Docker\docker.exe build .
      - run:
          name: "Run Docker app"
          shell: powershell.exe
          command: |
            C:\Docker\docker.exe run -d -p 8080:8080 mcr.microsoft.com/dotnet/core/samples:aspnetapp
      - run: 
          name: "Check Docker image listing"
          shell: powershell.exe
          command: |
            C:\Docker\docker.exe ps -a 
      - run: 
          name: "Docker daemon test"
          shell: powershell.exe
          command: |
            iwr -useb http://localhost:8080
