version: 2.1

#Comment

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    machine: true   
    resource_class: brianoh1979/brian-winrunner
    steps:
      - checkout
      - run: 
         command: C:\Windows\System32\OpenSSH\ssh-keyscan -H github.com >> ~/.ssh/known_hosts
         shell: powershell.exe
      - run:
          name: Authenticate gh and clone
          command: |
            # Authenticate
            echo "Authenticating GH CLI"
            #C:\GitHub-CLI\gh auth setup-git --hostname "github.com"
            #C:\GitHub-CLI\gh auth status
            # Configure
            echo "Disabling interactive prompts for GH CLI"
            C:\GitHub-CLI\gh config set prompt disabled
            C:\Git\bin\git clone --depth 2 git@github.com:brianoh1979/circleci-demo-macos.git C:\environment2
          shell: powershell.exe
