version: 2.1

#Comment

orbs:
  win: circleci/windows@1.0.0
  git-shallow-clone: guitarrapc/git-shallow-clone@2.4.0

jobs:
  build:
    machine: true
    resource_class: brianoh1979/brian-winrunner
    steps:
      - run:
          name: Install gh-cli
          command: |
            C:\ProgramData\chocolatey\bin\choco install gh -y #https://github.com/cli/cli#windows
          shell: powershell.exe
      - run:
          name: Authenticate gh and clone
          command: |
            # Authenticate
            echo "Authenticating GH CLI"
            C:\GitHub-CLI\gh auth setup-git --hostname "github.com"
            C:\GitHub-CLI\gh auth status

            # Configure
            echo "Disabling interactive prompts for GH CLI"
            C:\GitHub-CLI\gh config set prompt disabled

            C:\Git\bin\git clone --depth 2 https://github.com/brianoh1979/circleci-demo-macos .
          shell: powershell.exe
      - run:
          name: Demonstrate that we only have 2 commits
          command: C:\Git\bin\git\git log -5
 #     - run: cd "C:\Users\circleci.EC2AMAZ-H1LB92J"; ./git-shallow-clone.sh
 #     - run: 
 #        command: $env:brian
 #        shell: powershell.exe
 #     - restore_cache:
 #         keys:
 #           - dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}
 #     - run:
 #         name: "Install project dependencies"
 #         command: dotnet.exe restore
 #     - save_cache:
 #         paths:
 #           - C:\Users\circleci\.nuget\packages
 #         key: dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}

 #     - run:
 #         name: "Run Build step"
 #         command: dotnet.exe publish -c Release -r win10-x64
 #     - run:
 #         name: "Test the executable"
 #         command: .\bin\Release\netcoreapp2.1\win10-x64\publish\circleci-demo-windows.exe
 #     - store_artifacts:
 #         path: .\bin\Release\netcoreapp2.1\win10-x64\publish\circleci-demo-windows.exe
