version: 2.1

#Comment

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    machine: true   
    resource_class: brianoh1979/brian-winrunner
    steps:
      - checkout
      - run: 
          name: "Docker image build and tag"
          shell: powershell.exe
          command: |
            cd "C:\Program Files\Docker" ; docker build -t dotnetapp .
      - run: 
          name: "Check Docker image listing"
          shell: powershell.exe
          command: |
            cd "C:\Program Files\Docker" ; docker ps -a 
      - run: 
          name: "Docker daemon test"
          shell: powershell.exe
          command: |
            iwr -useb http://localhost:8080
