version: 2.1

#Comment

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    machine:
      image: 'windows-server-2022-gui:2022.08.1'
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - run: $PSVersionTable
      - run: cd "C:\WINDOWS\system32"; ./choco
#      - run: systeminfo
#      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
#      - shallow-checkout:
#          windows: true
      - run: 
         command: git clone --depth 5 "$CIRCLE_REPOSITORY_URL" --branch "$CIRCLE_BRANCH"
         shell: cmd.exe
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}

      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Release -r win10-x64
      - run:
          name: "Test the executable"
          command: .\bin\Release\netcoreapp2.1\win10-x64\publish\circleci-demo-windows.exe
      - store_artifacts:
          path: .\bin\Release\netcoreapp2.1\win10-x64\publish\circleci-demo-windows.exe
