version: 2.1

#Comment

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/windows/nanoserver:1809
      - image: nginx/nginx:latest
    steps:
      - checkout
      - run:
          name: "Get container NAT IP and run test curl command against container"
          shell: powershell.exe
          command: |
            Remove-item alias:curl
            curl --url http://${entrance}:8080
