version: 2.1

#Comment

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run: 
          name: "Docker image build and tag"
          shell: powershell.exe
          command: |
            docker build .
      - run:
          name: "Run Docker app"
          shell: powershell.exe
          command: |
            docker run -d -p 8080:8080 --name my-app mcr.microsoft.com/dotnet/core/samples:aspnetapp
      - run: 
          name: "Check Docker image listing"
          shell: powershell.exe
          command: |
            docker ps -a 
      - run:
          name: "Check Docker image listing"
          shell: powershell.exe
          command: |
            $entrance = docker inspect --format '{{ .NetworkSettings.Networks.nat.IPAddress }}' my-app
            echo $entrance
      - run: 
          name: "Docker container test"
          shell: powershell.exe
          command: |
            Remove-item alias:curl
            docker exec my-app curl --retry 2 --retry-connrefused --url "http://${entrance}:8080"
            docker exec my-app curl --retry 2 --retry-connrefused --url "http://${entrance}:80"
