version: 2.1

#Comment

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run: 
          name: "Docker image build and tag"
          shell: powershell.exe
          command: |
            docker build .
      - run:
          name: "Run Docker app"
          shell: powershell.exe
          command: |
            docker run -d -p 8080:8080 mcr.microsoft.com/dotnet/core/samples:aspnetapp
      - run: 
          name: "Check Docker image listing"
          shell: powershell.exe
          command: |
            docker ps -a 
#      - run: 
#          name: "Docker daemon test"
#          shell: powershell.exe
#          command: |
#            C:\Docker\docker.exe port test 8080/tcp
